# Generated by Django 4.0.3 on 2022-04-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='content',
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
